from Cython.Distutils import build_ext
from setuptools import setup,Extension
from numpy import get_include

ext_modules = [
    Extension('malio_cy.external_functions_cy',
               sources=['malio_cy/external_functions_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.misc_cy',
               sources=['malio_cy/misc_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_h_aha_cy',
               sources=['malio_cy/op_h_aha_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_t_msigma_cy',
               sources=['malio_cy/op_t_msigma_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_w_wigner_cy',
               sources=['malio_cy/op_w_wigner_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.neighbor_build_cy',
               sources=['malio_cy/neighbor_build_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_q_spherical_cy',
               sources=['malio_cy/op_q_spherical_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.wrapper_cy',
               sources=['malio_cy/wrapper_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_a_cnp_cy',
               sources=['malio_cy/op_a_cnp_cy.pyx'],
               include_dirs=[get_include()],language="c++"),
    Extension('malio_cy.op_d_nda_cy',
               sources=['malio_cy/op_d_nda_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_s_local_onsager_cy',
               sources=['malio_cy/op_s_local_onsager_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_b_baa_cy',
               sources=['malio_cy/op_b_baa_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_i_top_cy',
               sources=['malio_cy/op_i_top_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_f_afs_cy',
               sources=['malio_cy/op_f_afs_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_c_cpa_cy',
               sources=['malio_cy/op_c_cpa_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_z_user1_define_cy',
               sources=['malio_cy/op_z_user1_define_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_z_user2_define_cy',
               sources=['malio_cy/op_z_user2_define_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_z_user3_define_cy',
               sources=['malio_cy/op_z_user3_define_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_z_user4_define_cy',
               sources=['malio_cy/op_z_user4_define_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_z_user5_define_cy',
               sources=['malio_cy/op_z_user5_define_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.wigner_cy',
               sources=['malio_cy/wigner_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_lqw_spherical_cy',
               sources=['malio_cy/op_lqw_spherical_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_qw_spherical_cy',
               sources=['malio_cy/op_qw_spherical_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_qw1_spherical_cy',
               sources=['malio_cy/op_qw1_spherical_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++"),
    Extension('malio_cy.op_qw2_spherical_cy',
               sources=['malio_cy/op_qw2_spherical_cy.pyx'],
               include_dirs=[get_include()],
               extra_compile_args=['-O3'],language="c++")
]

#with open('README.rst') as f:
#    readme = f.read()

setup(
    name='malio_cy',
    packages=['malio_cy'],
    ext_modules=ext_modules,
    cmdclass={'build_ext': build_ext},
    version='0.1.0',
    description='cythonized malio',
    #long_description=readme,
    author='AIST',
    author_email='kazu.takahashi@aist.go.jp',
    url='https://github.com/Kazuaki-Z-Takahashi/MALIO',
    ## license=license,
    install_requires=['nose','numpy','pyquaternion','scipy','sympy','matplotlib','pandas','scikit-learn','cython'],
)
